name: 发布软件

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: GithubActionTest.sln
      Project_Path: GithubActionTest/GithubActionTest.csproj

    steps:
    - name: 提取代码
      uses: actions/checkout@v4

    - name: 设置 MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: 还原 NuGet 包
      run: nuget restore $env:Solution_Name

    - name: 构建解决方案
      run: msbuild $env:Solution_Name /p:Configuration=Release

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: BuildOutput
        path: GithubActionTest/bin/Release/
